apiVersion: v1
kind: Service
metadata:
  name: biny-manager-client
spec:
  selector:
    app: biny-manager-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biny-manager-client-deployment
  labels:
    app: biny-manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biny-manager-client
  template:
    metadata:
      labels:
        app: biny-manager-client
    spec:
      containers:
      - name: biny-manager-client
        image: cr.yandex/crpjb25rt61kq3pr2e1d/main:__VERSION__
        ports:
        - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biny-manager-client
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
      - app.biny.co
      secretName: k8s-secret
  #ingressClassName: nginx
  rules:
    - host: app.biny.co
      http:
        paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: biny-manager-client
              port:
                number: 3000
